apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    field.cattle.io/creatorId: u-ldwpzwsmnv
    field.cattle.io/publicEndpoints: '[{"addresses":["128.55.212.154"],"port":5432,"protocol":"TCP","serviceName":"bweaver:db-loadbalancer","allNodes":false}]'
    nersc.gov/collab_uids: 68595,58191,58102,33567
    nersc.gov/gid: "1034448"
    nersc.gov/gids: 1034448,1033567,2797,5529,43050,42636,51354,58102,58191,3860,68595,56023,57470,76870,96414
    nersc.gov/roles: user
    nersc.gov/uid: "34448"
    nersc.gov/username: bweaver
  creationTimestamp: "2023-01-18T22:34:03Z"
  generation: 20
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-bweaver-db
  name: db
  namespace: bweaver
  resourceVersion: "438771603"
  selfLink: /apis/apps/v1/namespaces/bweaver/deployments/db
  uid: fbfde2de-449f-4754-ab01-271521e5c4e7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-bweaver-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2023-01-19T19:38:44Z"
        field.cattle.io/ports: '[[{"containerPort":5432,"dnsName":"db-loadbalancer","hostPort":0,"kind":"LoadBalancer","name":"postgresql","protocol":"TCP","sourcePort":5432}]]'
        nersc.gov/collab_uids: 68595,58191,58102,33567
        nersc.gov/gid: "1034448"
        nersc.gov/gids: 1034448,1033567,2797,5529,43050,42636,51354,58102,58191,3860,68595,56023,57470,76870,96414
        nersc.gov/roles: user
        nersc.gov/uid: "34448"
        nersc.gov/username: bweaver
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-bweaver-db
    spec:
      containers:
      - env:
        - name: DESI_ADMIN_PASSWORD
          value: /secrets/desi_admin_password
        - name: DESI_PASSWORD
          value: /secrets/desi_password
        - name: POSTGRES_HOST_AUTH_METHOD
          value: md5
        - name: POSTGRES_PASSWORD_FILE
          value: /secrets/postgres_password_file
        image: registry.nersc.gov/desi/specprod/db:11-bullseye-q3c
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: db-secret-postgres
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-nersc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db-secret-postgres
        secret:
          defaultMode: 256
          optional: false
          secretName: db-bweaver-secrets
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-19T19:05:40Z"
    lastUpdateTime: "2023-01-19T19:05:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-19T19:22:04Z"
    lastUpdateTime: "2023-01-19T19:38:52Z"
    message: ReplicaSet "db-5dbcb9d47" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 20
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
